//The type of actions that we are going to have on aur application
const ADD_CATEGORY ='ADD_CATEGORY';
const ADD_CLOTHES ='ADD_CLOTHES';
const ADD_SET='ADD_SET';
const SEND_LOUNDRY ='SEND_LOUNDRY';
const SEND_MISSING ='SEND_MISSING';
const DELETE_MISSING ='DELETE_MISSING';
const DELETE_LOUNDRY ='DELETE_LOUNDRY';
const CATEGORY_SELECTED ='CATEGORY_SELECTED';
const SET_SELECTED = 'SET_SELECTED';
export {ADD_CATEGORY,ADD_CLOTHES,ADD_SET, SEND_LOUNDRY, SEND_MISSING, DELETE_LOUNDRY, DELETE_MISSING,CATEGORY_SELECTED,SET_SELECTED}
